# Generated by Django 3.2.6 on 2021-08-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=5)),
                ('to_currency', models.CharField(max_length=5)),
                ('rate', models.CharField(max_length=30)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['last_update'], name='app_exchang_last_up_6a5c5c_idx'),
        ),
    ]
